# Kafka particulars
server:
    host: "localhost"
    port: 9999
    username: ""
    password: ""
    domains:
        -   name: "\"kafka.server\""
            excludeObjects: ["\"Replica-MaxLag\""]
        -   name: "\"kafka.cluster\""
            excludeObjects: []
        -   name: "\"kafka.controller\""
            excludeObjects: []
        -   name: "\"kafka.network\""
            excludeObjects: []
        -   name: "\"kafka.log\""
            excludeObjects: []
        -   name: "\"kafka.consumer\""
            excludeObjects: []

#prefix used to show up metrics in AppDynamics
metricPathPrefix:  "Custom Metrics|Kafka|"

