# Kafka particulars
server:
    #Kafka host
    host: "localhost"
    #Kafka JMX port
    port: 9999
    username: ""
    password: ""
    domains:
        -   name: "kafka.server"
            excludeObjects: ["BytesInPerSec"]
        -   name: "kafka.cluster"
            excludeObjects: []
        -   name: "kafka.controller"
            excludeObjects: []
        -   name: "kafka.network"
            excludeObjects: []
        -   name: "kafka.log"
            excludeObjects: []
        -   name: "kafka.consumer"
            excludeObjects: []

#prefix used to show up metrics in AppDynamics
metricPathPrefix:  "Custom Metrics|Kafka|"